spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/imagelite
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true